-- SG Braunschweig Teampokal
-- In Supabase unter SQL Editor ausführen.

create table if not exists public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null check (role in ('member', 'admin'))
);

create table if not exists public.players (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 60),
  points integer not null default 0,
  updated_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.players enable row level security;

revoke all on table public.profiles from anon, authenticated;
revoke all on table public.players from anon, authenticated;

grant select on table public.profiles to authenticated;
grant select on table public.players to authenticated;
grant insert (name, points, updated_at) on table public.players to authenticated;
grant update (points, updated_at) on table public.players to authenticated;
grant delete on table public.players to authenticated;
grant usage, select on sequence public.players_id_seq to authenticated;

drop policy if exists "profiles_read_self" on public.profiles;
create policy "profiles_read_self"
on public.profiles
for select
to authenticated
using (user_id = auth.uid());

drop policy if exists "players_read_authenticated" on public.players;
create policy "players_read_authenticated"
on public.players
for select
to authenticated
using (true);

drop policy if exists "players_insert_admin" on public.players;
create policy "players_insert_admin"
on public.players
for insert
to authenticated
with check (
  exists (
    select 1
    from public.profiles
    where profiles.user_id = auth.uid()
      and profiles.role = 'admin'
  )
);

drop policy if exists "players_update_admin" on public.players;
create policy "players_update_admin"
on public.players
for update
to authenticated
using (
  exists (
    select 1
    from public.profiles
    where profiles.user_id = auth.uid()
      and profiles.role = 'admin'
  )
)
with check (
  exists (
    select 1
    from public.profiles
    where profiles.user_id = auth.uid()
      and profiles.role = 'admin'
  )
);

drop policy if exists "players_delete_admin" on public.players;
create policy "players_delete_admin"
on public.players
for delete
to authenticated
using (
  exists (
    select 1
    from public.profiles
    where profiles.user_id = auth.uid()
      and profiles.role = 'admin'
  )
);

-- Nach dem Anlegen der zwei Auth-Benutzer:
-- insert into public.profiles (user_id, role)
-- values
--   ('TEAM-USER-UUID-HIER', 'member'),
--   ('ADMIN-USER-UUID-HIER', 'admin')
-- on conflict (user_id) do update set role = excluded.role;
